// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJl7iUBpQD-czyLjeu7lHvejgULg2DK38',
    appId: '1:607289962644:web:1b9b5e4f5374a4616ec481',
    messagingSenderId: '607289962644',
    projectId: 'vaulta-7cdac',
    authDomain: 'vaulta-7cdac.firebaseapp.com',
    storageBucket: 'vaulta-7cdac.appspot.com',
    measurementId: 'G-HCP7LJC2X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLA6sUaGX7OTTsRTSilZRmC1zxpUNpag0',
    appId: '1:607289962644:android:c88423bf6c85ada16ec481',
    messagingSenderId: '607289962644',
    projectId: 'vaulta-7cdac',
    storageBucket: 'vaulta-7cdac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPc0_VMHaXxzFAqIslI-XRssHHScva4w',
    appId: '1:607289962644:ios:32a5bb9aee34e9cf6ec481',
    messagingSenderId: '607289962644',
    projectId: 'vaulta-7cdac',
    storageBucket: 'vaulta-7cdac.appspot.com',
    androidClientId: '607289962644-363fro429sfnrldsspeo3dcl9dl66275.apps.googleusercontent.com',
    iosClientId: '607289962644-edisk58hhund62l2tho351aign01ldpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaulta',
  );

}